backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "product"
    label: "Product"
    folder: "content/product"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Price", name: "price", widget: "number", valueType: "float" }
      - { label: "Featured", name: "featured", widget: "boolean" }
